# ==============================================================================
# PROJECT METADATA
# ==============================================================================

name: sw

description: >
  A command-line tool to generate service worker files for web applications.
  It simplifies the process of creating service workers.

version: 0.0.4

homepage: https://github.com/DoctorinaAI/service-worker-generator
repository: https://github.com/DoctorinaAI/service-worker-generator
issue_tracker: https://github.com/DoctorinaAI/service-worker-generator/issues

topics:
  - service-worker
  - generator
  - cli
  - web
  - flutter

platforms:
  linux:
  macos:
  windows:

# ==============================================================================
# PROJECT STRUCTURE
# ==============================================================================

# dart pub global activate --source path .
# dart run sw:generate
executables:
  generate: generate

# ==============================================================================
# DEPENDENCIES
# ==============================================================================

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  path: ^1.9.1
  args: ^2.7.0
  glob: ^2.1.3
  crypto: ^3.0.6

dev_dependencies:
  lints: ">=5.0.0 <7.0.0"
  test: ^1.26.2
