/**
 * Shared asset metadata and rendering helpers used by the asset copy and
 * verification scripts. Keeping the renderer in one place avoids drift
 * between "how we generate" and "how we verify".
 */

export const artifacts = [
  {
    input: 'packages/sw/dist/sw.js',
    output: 'lib/src/assets/sw_template.dart',
    constName: 'swTemplate',
    description: 'Compiled service worker JavaScript template.',
  },
  {
    input: 'packages/sw/dist/bootstrap.js',
    output: 'lib/src/assets/bootstrap_template.dart',
    constName: 'bootstrapTemplate',
    description: 'Compiled bootstrap JavaScript template.',
  },
];

export function renderDartAsset({ input, constName, description }, js) {
  // Escape sequences that would break Dart raw string literals.
  // If JS contains triple single-quotes, split into concatenated strings.
  let dartContent;
  if (js.includes("'''")) {
    const parts = js.split("'''");
    const escaped = parts
      .map((part, index) =>
        index < parts.length - 1 ? `${part}\\'\\'\\' ` : part,
      )
      .join('');
    dartContent = `r'''\n${escaped}'''`;
  } else {
    dartContent = `r'''\n${js}'''`;
  }

  return `// GENERATED FILE - DO NOT EDIT
// Generated by scripts/copy-assets.mjs
// Source: ${input}

/// ${description}
/// Contains placeholder tokens that the CLI replaces with actual
/// configuration at generation time.
const String ${constName} = ${dartContent};
`;
}

export function normalizeTextForComparison(text) {
  return text.replace(/\r\n/g, '\n');
}
