#!/usr/bin/env node

/**
 * Copies compiled JS artifacts from packages/sw/dist/
 * into Dart string constants in lib/src/assets/.
 *
 * Usage: node scripts/copy-assets.mjs
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

const artifacts = [
  {
    input: 'packages/sw/dist/sw.js',
    output: 'lib/src/assets/sw_template.dart',
    constName: 'swTemplate',
    description: 'Compiled service worker JavaScript template.',
  },
  {
    input: 'packages/sw/dist/bootstrap.js',
    output: 'lib/src/assets/bootstrap_template.dart',
    constName: 'bootstrapTemplate',
    description: 'Compiled bootstrap JavaScript template.',
  },
];

for (const { input, output, constName, description } of artifacts) {
  const inputPath = resolve(root, input);
  const outputPath = resolve(root, output);

  if (!existsSync(inputPath)) {
    console.error(`ERROR: ${input} not found. Run 'npm run build' first.`);
    process.exit(1);
  }

  const js = readFileSync(inputPath, 'utf-8');

  // Escape sequences that would break Dart raw string literals.
  // If JS contains triple single-quotes, split into concatenated strings.
  let dartContent;
  if (js.includes("'''")) {
    // Split around ''' and concatenate
    const parts = js.split("'''");
    const escaped = parts
      .map((p, i) => (i < parts.length - 1 ? `${p}\\'\\'\\' ` : p))
      .join('');
    dartContent = `r'''\n${escaped}'''`;
  } else {
    dartContent = `r'''\n${js}'''`;
  }

  const dart = `// GENERATED FILE - DO NOT EDIT
// Generated by scripts/copy-assets.mjs
// Source: ${input}

/// ${description}
/// Contains placeholder tokens that the CLI replaces with actual
/// configuration at generation time.
const String ${constName} = ${dartContent};
`;

  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, dart, 'utf-8');

  const sizeKB = (js.length / 1024).toFixed(1);
  console.log(`  ${input} (${sizeKB} KB) → ${output}`);
}

console.log('Assets copied successfully.');
